theme = "catppuccin_mocha"

[keys.normal]
C-d = ":half-page-down-smooth"
C-u = ":half-page-up-smooth"
pageup = ":page-up-smooth"
pagedown = ":page-down-smooth"

space.e = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi "%{buffer_name}" --chooser-file=/tmp/unique-file',
  ':sh printf "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
]
