# Personal-only applications and services.
#
# Gated by `dotfiles.personal.enable` (default false). Per-app toggles
# default to true so personal machines flip a single switch and pick
# up everything; new personal apps added here are opt-out for existing
# personal hosts and inert on work hosts.
#
# Cross-platform behaviour:
#
#   - Signal: `pkgs.signal-desktop` on both Linux and macOS. nixpkgs
#     8.8.0 ships Darwin builds (verified in nixpkgs PR #513155 and
#     #514760 nixpkgs-review CI runs); the install phase produces
#     `$out/Applications/Signal.app` on Darwin which is aliased into
#     `~/Applications/Nix Apps` by `home/darwin-apps.nix`.
#   - Syncthing: Home Manager service (`services.syncthing`) — systemd
#     user unit on Linux, launchd agent on macOS.
#   - Tailscale: Nix CLI on Linux. macOS uses the official Tailscale
#     app installed via a Homebrew-managed cask, because `pkgs.tailscale` ships
#     only `tailscale`/`tailscaled` and the user-facing GUI lives in
#     the App Store / Brew cask.
#   - NAPS2: `pkgs.naps2` on Linux. macOS uses the official Homebrew cask.
#   - Immich CLI: `pkgs.immich-cli` on personal hosts only.
#
# Cask lines for Darwin-only apps (Tailscale, Chromium, NAPS2 today) are appended to a
# generated `Brewfile.personal`; `setup.sh` reconciles it alongside
# the static `config/Brewfile`.
{
  config,
  inputs,
  lib,
  nixglNvidia ? null,
  pkgs,
  ...
}:

let
  privatePersonal = inputs.private.personal or { };
  privateSignal = privatePersonal.signal or { };
  privateSyncthing = privatePersonal.syncthing or { };
  privateChromium = privatePersonal.chromium or { };
  privateNaps2 = privatePersonal.naps2 or { };
  privateTailscale = privatePersonal.tailscale or { };
  privatePlezy = privatePersonal.plezy or { };
  privateImmich = privatePersonal.immich or { };
  # Dashed keys: only hosts whose private overlay opts in run these
  # exporters. See infra/arch-printer-exporter in homeserver/grafana-dashboards.
  privatePrinterExporter = privatePersonal."printer-exporter" or { };
  privateCupsExporter = privatePersonal."cups-exporter" or { };
  privateMaintenanceExporter = privatePersonal."brother-maintenance-exporter" or { };
  privateOpencodeExporter = privatePersonal."opencode-exporter" or { };
  privateOpencodeIngress = privatePersonal."opencode-ingress" or { };
  privateUnifiExporter = privatePersonal."unifi-exporter" or { };

  printerExporterUrl =
    bindAddress: "http://${bindAddress}/metrics";

  cfg = config.dotfiles.personal;

  plezyPackage =
    if pkgs.stdenv.isLinux && inputs ? nixgl && inputs ? nixgl-nixpkgs then
      let
        wrapWithNixGL = import ./lib/wrap-with-nixgl.nix {
          inherit pkgs nixglNvidia;
          inherit (inputs) nixgl nixgl-nixpkgs;
        };
      in
      wrapWithNixGL pkgs.plezy "plezy"
    else
      pkgs.plezy;

  # Personal Homebrew-managed casks. Add new entries as `cask "name"` lines
  # gated by their respective per-app toggle. Empty when no personal
  # cask applies to this host — `setup.sh` skips a missing file.
  personalBrewfileLines =
    lib.optionals (cfg.tailscale.enable && pkgs.stdenv.isDarwin) [ ''cask "tailscale-app"'' ]
    ++ lib.optionals (cfg.chromium.enable && pkgs.stdenv.isDarwin) [ ''cask "chromium"'' ]
    ++ lib.optionals (cfg.naps2.enable && pkgs.stdenv.isDarwin) [ ''cask "naps2"'' ];

  personalBrewfileText = ''
    # Generated by home/personal.nix. Do not edit; toggle entries via
    # `dotfiles.personal.*.enable` in your private flake.
  ''
  + lib.concatStringsSep "\n" personalBrewfileLines
  + "\n";
in
{
  options.dotfiles.personal = {
    enable = lib.mkOption {
      type = lib.types.bool;
      default = privatePersonal.enable or false;
      description = ''
        Master switch for personal-only applications and services.
        Leave false on work machines. When true, every per-app toggle
        defaults to enabled — opt out of individual apps below.
      '';
    };

    signal.enable = lib.mkOption {
      type = lib.types.bool;
      default = privateSignal.enable or true;
      description = ''
        Install Signal Desktop. Nix-managed (`pkgs.signal-desktop`) on
        both Linux and macOS.
      '';
    };

    syncthing.enable = lib.mkOption {
      type = lib.types.bool;
      default = privateSyncthing.enable or true;
      description = "Run the Syncthing user service (systemd on Linux, launchd on macOS).";
    };

    tailscale.enable = lib.mkOption {
      type = lib.types.bool;
      default = privateTailscale.enable or true;
      description = ''
        Install Tailscale. On Linux this installs the `tailscale` CLI
        (the privileged `tailscaled` daemon still needs host setup).
        On macOS this declares a Homebrew-managed cask for the official
        Tailscale app — the host-level system extension still has to
        be approved manually.
      '';
    };

    chromium.enable = lib.mkOption {
      type = lib.types.bool;
      default = privateChromium.enable or true;
      description = ''
        Install Chromium. On Linux this uses `pkgs.chromium` with Widevine
        enabled. On macOS this declares a Homebrew-managed cask for the
        official Chromium app.
      '';
    };

    naps2.enable = lib.mkOption {
      type = lib.types.bool;
      default = privateNaps2.enable or true;
      description = ''
        Install NAPS2 document scanner. On Linux this uses `pkgs.naps2`.
        On macOS this declares a Homebrew-managed cask for the official app.
      '';
    };

    plezy.enable = lib.mkOption {
      type = lib.types.bool;
      default = privatePlezy.enable or true;
      description = ''
        Install Plezy, a modern Plex & Jellyfin client. Uses `pkgs.plezy`
        from nixpkgs on all supported platforms.
      '';
    };

    immich.enable = lib.mkOption {
      type = lib.types.bool;
      default = privateImmich.enable or true;
      description = "Install the Immich CLI for photo management on personal hosts.";
    };

    printerExporter.enable = lib.mkOption {
      type = lib.types.bool;
      default = privatePrinterExporter.enable or false;
      description = ''
        Run the Brother printer snmp_exporter bridge as a user service.
        Defaults to false because only hosts on the printer's home LAN can
        reach the device; the private overlay opts in per host and supplies
        bindAddress and configFile.
      '';
    };

    printerExporter.bindAddress = lib.mkOption {
      type = lib.types.str;
      default = privatePrinterExporter.bindAddress or "127.0.0.1:9116";
      description = ''
        Address the exporter binds. Use the host's Tailscale IPv4 so
        exposure is governed by the tailnet policy alone.
      '';
    };

    printerExporter.configFile = lib.mkOption {
      type = lib.types.nullOr lib.types.path;
      default = privatePrinterExporter.configFile or null;
      description = "snmp_exporter module configuration (snmp.yml) for the printer.";
    };

    cupsExporter.enable = lib.mkOption {
      type = lib.types.bool;
      default = privateCupsExporter.enable or false;
      description = ''
        Run the CUPS prometheus exporter as a user service. Defaults to
        false because only hosts running a CUPS server have something to
        export; the private overlay opts in per host and supplies
        bindAddress.
      '';
    };

    cupsExporter.bindAddress = lib.mkOption {
      type = lib.types.str;
      default = privateCupsExporter.bindAddress or "127.0.0.1:9628";
      description = ''
        Address the exporter binds. Use the host's Tailscale IPv4 so
        exposure is governed by the tailnet policy alone.
      '';
    };

    cupsExporter.cupsUri = lib.mkOption {
      type = lib.types.str;
      default = privateCupsExporter.cupsUri or "http://localhost:631";
      description = "URI of the CUPS server the exporter queries over IPP/HTTP.";
    };

    printerMaintenanceExporter.enable = lib.mkOption {
      type = lib.types.bool;
      default = privateMaintenanceExporter.enable or false;
      description = ''
        Run the Brother maintenance-info exporter (toner/drum/tray percentages
        decoded from private OIDs) as a user service. Defaults to false
        because only hosts on the printer's home LAN can reach the device;
        the private overlay opts in per host and supplies bindAddress.
      '';
    };

    printerMaintenanceExporter.bindAddress = lib.mkOption {
      type = lib.types.str;
      default = privateMaintenanceExporter.bindAddress or "127.0.0.1:9629";
      description = ''
        Address the exporter binds. Use the host's Tailscale IPv4 so
        exposure is governed by the tailnet policy alone.
      '';
    };

    printerMaintenanceExporter.snmpHost = lib.mkOption {
      type = lib.types.str;
      default = privateMaintenanceExporter.snmpHost or "192.168.0.158";
      description = "LAN address of the Brother printer to poll over SNMPv1.";
    };

    opencodeExporter.enable = lib.mkOption {
      type = lib.types.bool;
      default = privateOpencodeExporter.enable or false;
      description = ''
        Run the OpenCode shared-server usage exporter as a user service.
        Defaults to false because it is only useful on hosts running the
        shared OpenCode server that monitoring should scrape; the private
        overlay opts in per host and supplies bindAddress.
      '';
    };

    opencodeExporter.bindAddress = lib.mkOption {
      type = lib.types.str;
      default = privateOpencodeExporter.bindAddress or "127.0.0.1:9630";
      description = ''
        Address the exporter binds. Use the host's Tailscale IPv4 so
        exposure is governed by the tailnet policy alone.
      '';
    };

    opencodeExporter.serverUrl = lib.mkOption {
      type = lib.types.str;
      default = privateOpencodeExporter.serverUrl or "http://127.0.0.1:4096";
      description = ''
        Base URL of the local shared OpenCode server
        (programs.opencode.sharedServer) to poll.
      '';
    };

    unifiExporter.enable = lib.mkOption {
      type = lib.types.bool;
      default = privateUnifiExporter.enable or false;
      description = ''
        Run unpoller (UniFi controller Prometheus exporter) as a user service.
        Defaults to false because only hosts on the UniFi console's home LAN
        can reach it; the private overlay opts in per host and supplies
        bindAddress and configFile.
      '';
    };

    unifiExporter.bindAddress = lib.mkOption {
      type = lib.types.str;
      default = privateUnifiExporter.bindAddress or "127.0.0.1:9130";
      description = ''
        Address the exporter binds. Use the host's Tailscale IPv4 so
        exposure is governed by the tailnet policy alone.
      '';
    };

    unifiExporter.configFile = lib.mkOption {
      type = lib.types.nullOr lib.types.path;
      default = privateUnifiExporter.configFile or null;
      description = ''
        unpoller TOML configuration (controller URL plus credentials). Must
        be supplied by the private overlay because it contains secrets.
      '';
    };

    opencodeExporter.authFile = lib.mkOption {
      type = lib.types.path;
      default = privateOpencodeExporter.authFile or "${config.xdg.dataHome}/opencode/auth.json";
      description = ''
        OpenCode auth file read for subscription quota collection
        (ai_subscription_quota_* metrics). Must belong to the user running
        the exporter; credentials are never logged or exported.
      '';
    };

    opencodeIngress.enable = lib.mkOption {
      type = lib.types.bool;
      default = privateOpencodeIngress.enable or false;
      description = ''
        Run a Tailscale-only TCP bridge to the local shared OpenCode server.
        The private overlay opts in only on the Arch host.
      '';
    };

    opencodeIngress.bindAddress = lib.mkOption {
      type = lib.types.str;
      default = privateOpencodeIngress.bindAddress or "127.0.0.1";
      description = "IPv4 address on which the OpenCode ingress bridge listens.";
    };

    opencodeIngress.port = lib.mkOption {
      type = lib.types.port;
      default = privateOpencodeIngress.port or 4097;
      description = "TCP port on which the OpenCode ingress bridge listens.";
    };

    opencodeIngress.allowedSource = lib.mkOption {
      type = lib.types.str;
      default = privateOpencodeIngress.allowedSource or "127.0.0.1/32";
      description = ''
        Source IPv4 range accepted by the OpenCode ingress bridge. This must be
        the Edge Tailscale address, not a broad Tailnet range.
      '';
    };
  };

  config =
    lib.mkIf
      cfg.enable
      (lib.mkMerge [
        {
          home.packages =
            lib.optionals cfg.signal.enable [ pkgs.signal-desktop ]
            ++ lib.optionals (cfg.chromium.enable && pkgs.stdenv.isLinux) [
              (pkgs.chromium.override { enableWideVine = true; })
            ]
            ++ lib.optionals (cfg.naps2.enable && pkgs.stdenv.isLinux) [ pkgs.naps2 ]
            ++ lib.optionals (cfg.tailscale.enable && pkgs.stdenv.isLinux) [ pkgs.tailscale ]
            ++ lib.optionals cfg.plezy.enable [ plezyPackage ]
            ++ lib.optionals cfg.immich.enable [ pkgs.immich-cli ];

          services.syncthing = lib.mkIf cfg.syncthing.enable {
            enable = true;
            extraOptions = [ "--allow-newer-config" ];
          };

          # Only write Brewfile.personal on Darwin and only when at least
          # one cask is selected. Skipping the file entirely when empty
          # keeps `setup.sh` quiet on unaffected hosts.
          xdg.configFile."dotfiles-managed/Brewfile.personal" = lib.mkIf (
            pkgs.stdenv.isDarwin && personalBrewfileLines != [ ]
          ) { text = personalBrewfileText; };
        }
        (lib.mkIf (cfg.printerExporter.enable && pkgs.stdenv.isLinux) (
          let
            bindAddress = cfg.printerExporter.bindAddress;
            configFile =
              if cfg.printerExporter.configFile == null then
                throw "dotfiles.personal.printerExporter.configFile must be supplied by the private overlay when the printer exporter is enabled."
              else
                cfg.printerExporter.configFile;
            exporterUrl = printerExporterUrl bindAddress;
            execArgs = [
              "${pkgs.prometheus-snmp-exporter}/bin/snmp_exporter"
              "--config.file=${toString configFile}"
              "--web.listen-address=${bindAddress}"
            ];
          in
          (import ./lib/managed-user-service.nix) { inherit config pkgs lib; } {
            activationName = "printerExporter";
            changedMessage = "Printer exporter inputs changed; restarting service";
            darwinProgramArguments = execArgs;
            deferredFollowup = "Run setup.sh from a normal shell to restart the printer exporter safely";
            deferredMessage = "Printer exporter inputs changed; restart deferred because setup is running under an OpenCode agent";
            description = "Brother printer SNMP exporter bridge";
            environment = { };
            errorLogFile = "${config.xdg.dataHome}/printer-exporter/error.log";
            # The exporter's own /metrics endpoint answers even while the
            # printer is asleep, so health checks never loop-restart it.
            healthCommand = ''${pkgs.curl}/bin/curl --fail --silent --max-time 2 '${exporterUrl}' >/dev/null 2>&1'';
            label = "dev.printer.exporter";
            linuxExecStart = lib.escapeShellArgs execArgs;
            linuxService.TimeoutStopSec = "10s";
            logFile = "${config.xdg.dataHome}/printer-exporter/log";
            markerFile = "${config.xdg.cacheHome}/dotfiles/printer-exporter.sha256";
            occupiedHint = "If ${bindAddress} is held by an old exporter process, kill it manually and rerun setup.sh";
            restartFailureWarning = "Printer exporter restart failed or did not become healthy at ${exporterUrl}";
            serviceFingerprint = builtins.toJSON {
              inherit bindAddress;
              bin = toString pkgs.prometheus-snmp-exporter;
            };
            systemdService = "printer-exporter.service";
            systemdUnitName = "printer-exporter";
            url = exporterUrl;
            waitAttempts = 50;
            waitDescription = "printer exporter";
            watchedPaths = [ (toString configFile) ];
            workingDirectory = config.home.homeDirectory;
          }
        ))
        (lib.mkIf (cfg.cupsExporter.enable && pkgs.stdenv.isLinux) (
          let
            bindAddress = cfg.cupsExporter.bindAddress;
            cupsUri = cfg.cupsExporter.cupsUri;
            exporterUrl = printerExporterUrl bindAddress;
            execArgs = [
              "${pkgs.cups-exporter}/bin/cups_exporter"
              "-cups.uri=${cupsUri}"
              "-web.listen-address=${bindAddress}"
            ];
          in
          (import ./lib/managed-user-service.nix) { inherit config pkgs lib; } {
            activationName = "cupsExporter";
            changedMessage = "CUPS exporter inputs changed; restarting service";
            darwinProgramArguments = execArgs;
            deferredFollowup = "Run setup.sh from a normal shell to restart the CUPS exporter safely";
            deferredMessage = "CUPS exporter inputs changed; restart deferred because setup is running under an OpenCode agent";
            description = "CUPS print-server prometheus exporter";
            environment = { };
            errorLogFile = "${config.xdg.dataHome}/cups-exporter/error.log";
            # The exporter's /metrics endpoint answers even while the queue
            # is empty or a printer is offline, so health checks never
            # loop-restart it.
            healthCommand = ''${pkgs.curl}/bin/curl --fail --silent --max-time 2 '${exporterUrl}' >/dev/null 2>&1'';
            label = "dev.cups.exporter";
            linuxExecStart = lib.escapeShellArgs execArgs;
            linuxService.TimeoutStopSec = "10s";
            logFile = "${config.xdg.dataHome}/cups-exporter/log";
            markerFile = "${config.xdg.cacheHome}/dotfiles/cups-exporter.sha256";
            occupiedHint = "If ${bindAddress} is held by an old exporter process, kill it manually and rerun setup.sh";
            restartFailureWarning = "CUPS exporter restart failed or did not become healthy at ${exporterUrl}";
            serviceFingerprint = builtins.toJSON {
              inherit bindAddress cupsUri;
              bin = toString pkgs.cups-exporter;
            };
            systemdService = "cups-exporter.service";
            systemdUnitName = "cups-exporter";
            url = exporterUrl;
            waitAttempts = 50;
            waitDescription = "CUPS exporter";
            watchedPaths = [ ];
            workingDirectory = config.home.homeDirectory;
          }
        ))
        (lib.mkIf (cfg.printerMaintenanceExporter.enable && pkgs.stdenv.isLinux) (
          let
            bindAddress = cfg.printerMaintenanceExporter.bindAddress;
            snmpHost = cfg.printerMaintenanceExporter.snmpHost;
            exporterUrl = printerExporterUrl bindAddress;
            execArgs = [
              "${pkgs.brother-maintenance-exporter}/bin/brother-maintenance-exporter"
              "--bind=${bindAddress}"
              "--snmp-host=${snmpHost}"
            ];
          in
          (import ./lib/managed-user-service.nix) { inherit config pkgs lib; } {
            activationName = "printerMaintenanceExporter";
            changedMessage = "Brother maintenance exporter inputs changed; restarting service";
            darwinProgramArguments = execArgs;
            deferredFollowup = "Run setup.sh from a normal shell to restart the Brother maintenance exporter safely";
            deferredMessage = "Brother maintenance exporter restart deferred because setup is running under an OpenCode agent";
            description = "Brother printer maintenance-info prometheus exporter";
            environment = { };
            errorLogFile = "${config.xdg.dataHome}/brother-maintenance-exporter/error.log";
            # The exporter always answers /metrics (brother_maintenance_up 0 on
            # scrape failure), so health checks never loop-restart it.
            healthCommand = ''${pkgs.curl}/bin/curl --fail --silent --max-time 2 '${exporterUrl}' >/dev/null 2>&1'';
            label = "dev.brother.maintenance";
            linuxExecStart = lib.escapeShellArgs execArgs;
            linuxService.TimeoutStopSec = "10s";
            logFile = "${config.xdg.dataHome}/brother-maintenance-exporter/log";
            markerFile = "${config.xdg.cacheHome}/dotfiles/brother-maintenance-exporter.sha256";
            occupiedHint = "If ${bindAddress} is held by an old exporter process, kill it manually and rerun setup.sh";
            restartFailureWarning = "Brother maintenance exporter restart failed or did not become healthy at ${exporterUrl}";
            serviceFingerprint = builtins.toJSON {
              inherit bindAddress snmpHost;
              bin = toString pkgs.brother-maintenance-exporter;
            };
            systemdService = "brother-maintenance-exporter.service";
            systemdUnitName = "brother-maintenance-exporter";
            url = exporterUrl;
            waitAttempts = 50;
            waitDescription = "Brother maintenance exporter";
            watchedPaths = [ ];
            workingDirectory = config.home.homeDirectory;
          }
        ))
        (lib.mkIf (cfg.opencodeExporter.enable && pkgs.stdenv.isLinux) (
          let
            bindAddress = cfg.opencodeExporter.bindAddress;
            serverUrl = cfg.opencodeExporter.serverUrl;
            authFile = cfg.opencodeExporter.authFile;
            exporterUrl = printerExporterUrl bindAddress;
            execArgs = [
              "${pkgs.opencode-exporter}/bin/opencode-exporter"
              "--bind=${bindAddress}"
              "--server-url=${serverUrl}"
              "--auth-file=${authFile}"
            ];
          in
          (import ./lib/managed-user-service.nix) { inherit config pkgs lib; } {
            activationName = "opencodeExporter";
            changedMessage = "OpenCode exporter inputs changed; restarting service";
            darwinProgramArguments = execArgs;
            deferredFollowup = "Run setup.sh from a normal shell to restart the OpenCode exporter safely";
            deferredMessage = "OpenCode exporter inputs changed; restart deferred because setup is running under an OpenCode agent";
            description = "OpenCode shared-server usage prometheus exporter";
            environment = { };
            errorLogFile = "${config.xdg.dataHome}/opencode-exporter/error.log";
            # The exporter always answers /metrics (opencode_up 0 when the
            # shared server is down), so health checks never loop-restart it.
            healthCommand = ''${pkgs.curl}/bin/curl --fail --silent --max-time 2 '${exporterUrl}' >/dev/null 2>&1'';
            label = "dev.opencode.exporter";
            linuxExecStart = lib.escapeShellArgs execArgs;
            linuxService.TimeoutStopSec = "10s";
            logFile = "${config.xdg.dataHome}/opencode-exporter/log";
            markerFile = "${config.xdg.cacheHome}/dotfiles/opencode-exporter.sha256";
            occupiedHint = "If ${bindAddress} is held by an old exporter process, kill it manually and rerun setup.sh";
            restartFailureWarning = "OpenCode exporter restart failed or did not become healthy at ${exporterUrl}";
            serviceFingerprint = builtins.toJSON {
              inherit bindAddress serverUrl authFile;
              bin = toString pkgs.opencode-exporter;
            };
            systemdService = "opencode-exporter.service";
            systemdUnitName = "opencode-exporter";
            url = exporterUrl;
            waitAttempts = 50;
            waitDescription = "OpenCode exporter";
            watchedPaths = [ ];
            workingDirectory = config.home.homeDirectory;
          }
        ))
        (lib.mkIf (cfg.unifiExporter.enable && pkgs.stdenv.isLinux) (
          let
            bindAddress = cfg.unifiExporter.bindAddress;
            configFile =
              if cfg.unifiExporter.configFile == null then
                throw "dotfiles.personal.unifiExporter.configFile must be supplied by the private overlay when the UniFi exporter is enabled."
              else
                cfg.unifiExporter.configFile;
            exporterUrl = printerExporterUrl bindAddress;
            execArgs = [
              "${pkgs.unpoller}/bin/unpoller"
              "--config=${toString configFile}"
            ];
          in
          (import ./lib/managed-user-service.nix) { inherit config pkgs lib; } {
            activationName = "unifiExporter";
            changedMessage = "UniFi exporter inputs changed; restarting service";
            darwinProgramArguments = execArgs;
            deferredFollowup = "Run setup.sh from a normal shell to restart the UniFi exporter safely";
            deferredMessage = "UniFi exporter inputs changed; restart deferred because setup is running under an OpenCode agent";
            description = "UniFi controller unpoller prometheus exporter";
            environment = { };
            errorLogFile = "${config.xdg.dataHome}/unifi-exporter/error.log";
            # unpoller keeps serving /metrics from its cached snapshot even
            # while the console is unreachable, so health checks never
            # loop-restart it.
            healthCommand = ''${pkgs.curl}/bin/curl --fail --silent --max-time 2 '${exporterUrl}' >/dev/null 2>&1'';
            label = "dev.unifi.exporter";
            linuxExecStart = lib.escapeShellArgs execArgs;
            linuxService.TimeoutStopSec = "10s";
            logFile = "${config.xdg.dataHome}/unifi-exporter/log";
            markerFile = "${config.xdg.cacheHome}/dotfiles/unifi-exporter.sha256";
            occupiedHint = "If ${bindAddress} is held by an old exporter process, kill it manually and rerun setup.sh";
            restartFailureWarning = "UniFi exporter restart failed or did not become healthy at ${exporterUrl}";
            serviceFingerprint = builtins.toJSON {
              inherit bindAddress;
              bin = toString pkgs.unpoller;
            };
            systemdService = "unifi-exporter.service";
            systemdUnitName = "unifi-exporter";
            url = exporterUrl;
            waitAttempts = 50;
            waitDescription = "UniFi exporter";
            watchedPaths = [ (toString configFile) ];
            workingDirectory = config.home.homeDirectory;
          }
        ))
        (lib.mkIf (cfg.opencodeIngress.enable && pkgs.stdenv.isLinux) (
          let
            bindAddress = cfg.opencodeIngress.bindAddress;
            port = toString cfg.opencodeIngress.port;
            allowedSource = cfg.opencodeIngress.allowedSource;
            listenUrl = "http://${bindAddress}:${port}";
            execArgs = [
              "${pkgs.socat}/bin/socat"
              "TCP-LISTEN:${port},bind=${bindAddress},fork,reuseaddr,range=${allowedSource}"
              "TCP:127.0.0.1:4096"
            ];
          in
          (import ./lib/managed-user-service.nix) { inherit config pkgs lib; } {
            activationName = "opencodeIngress";
            changedMessage = "OpenCode ingress inputs changed; restarting service";
            darwinProgramArguments = execArgs;
            deferredFollowup = "Run setup.sh from a normal shell to restart the OpenCode ingress safely";
            deferredMessage = "OpenCode ingress inputs changed; restart deferred because setup is running under an OpenCode agent";
            description = "Tailscale-only OpenCode ingress bridge";
            environment = { };
            errorLogFile = "${config.xdg.dataHome}/opencode-ingress/error.log";
            healthCommand = ''${pkgs.curl}/bin/curl --fail --silent --max-time 2 http://127.0.0.1:4096/global/health >/dev/null 2>&1'';
            label = "dev.opencode.ingress";
            linuxExecStart = lib.escapeShellArgs execArgs;
            linuxService.TimeoutStopSec = "10s";
            logFile = "${config.xdg.dataHome}/opencode-ingress/log";
            markerFile = "${config.xdg.cacheHome}/dotfiles/opencode-ingress.sha256";
            occupiedHint = "If ${listenUrl} is held by an old ingress process, kill it manually and rerun setup.sh";
            restartFailureWarning = "OpenCode ingress restart failed or did not become healthy at ${listenUrl}";
            serviceFingerprint = builtins.toJSON {
              inherit allowedSource bindAddress port;
              bin = toString pkgs.socat;
            };
            systemdService = "opencode-ingress.service";
            systemdUnitName = "opencode-ingress";
            url = listenUrl;
            waitAttempts = 50;
            waitDescription = "OpenCode ingress";
            watchedPaths = [ ];
            workingDirectory = config.home.homeDirectory;
          }
        ))
      ]);
}
