# Personal-only applications and services.
#
# Gated by `dotfiles.personal.enable` (default false). Per-app toggles
# default to true so personal machines flip a single switch and pick
# up everything; new personal apps added here are opt-out for existing
# personal hosts and inert on work hosts.
#
# Cross-platform behaviour:
#
#   - Signal: `pkgs.signal-desktop` on both Linux and macOS. nixpkgs
#     8.8.0 ships Darwin builds (verified in nixpkgs PR #513155 and
#     #514760 nixpkgs-review CI runs); the install phase produces
#     `$out/Applications/Signal.app` on Darwin which is aliased into
#     `~/Applications/Nix Apps` by `home/darwin-apps.nix`.
#   - Syncthing: Home Manager service (`services.syncthing`) — systemd
#     user unit on Linux, launchd agent on macOS.
#   - Tailscale: Nix CLI on Linux. macOS uses the official Tailscale
#     app installed via Homebrew cask, because `pkgs.tailscale` ships
#     only `tailscale`/`tailscaled` and the user-facing GUI lives in
#     the App Store / Brew cask.
#
# Cask lines for Darwin-only apps (Tailscale, Chromium today) are appended to a
# generated `Brewfile.personal`; `setup.sh` reconciles it alongside
# the static `config/Brewfile`.
{
  config,
  inputs,
  lib,
  pkgs,
  ...
}:

let
  privatePersonal = inputs.private.personal or { };
  privateSignal = privatePersonal.signal or { };
  privateSyncthing = privatePersonal.syncthing or { };
  privateChromium = privatePersonal.chromium or { };
  privateTailscale = privatePersonal.tailscale or { };

  cfg = config.dotfiles.personal;

  # Personal Homebrew casks. Add new entries as `cask "name"` lines
  # gated by their respective per-app toggle. Empty when no personal
  # cask applies to this host — `setup.sh` skips a missing file.
  personalBrewfileLines =
    lib.optionals (cfg.tailscale.enable && pkgs.stdenv.isDarwin) [ ''cask "tailscale"'' ]
    ++ lib.optionals (cfg.chromium.enable && pkgs.stdenv.isDarwin) [ ''cask "chromium"'' ];

  personalBrewfileText = ''
    # Generated by home/personal.nix. Do not edit; toggle entries via
    # `dotfiles.personal.*.enable` in your private flake.
  ''
  + lib.concatStringsSep "\n" personalBrewfileLines
  + "\n";
in
{
  options.dotfiles.personal = {
    enable = lib.mkOption {
      type = lib.types.bool;
      default = privatePersonal.enable or false;
      description = ''
        Master switch for personal-only applications and services.
        Leave false on work machines. When true, every per-app toggle
        defaults to enabled — opt out of individual apps below.
      '';
    };

    signal.enable = lib.mkOption {
      type = lib.types.bool;
      default = privateSignal.enable or true;
      description = ''
        Install Signal Desktop. Nix-managed (`pkgs.signal-desktop`) on
        both Linux and macOS.
      '';
    };

    syncthing.enable = lib.mkOption {
      type = lib.types.bool;
      default = privateSyncthing.enable or true;
      description = "Run the Syncthing user service (systemd on Linux, launchd on macOS).";
    };

    tailscale.enable = lib.mkOption {
      type = lib.types.bool;
      default = privateTailscale.enable or true;
      description = ''
        Install Tailscale. On Linux this installs the `tailscale` CLI
        (the privileged `tailscaled` daemon still needs host setup).
        On macOS this declares a Homebrew cask for the official
        Tailscale app — the host-level system extension still has to
        be approved manually.
      '';
    };

    chromium.enable = lib.mkOption {
      type = lib.types.bool;
      default = privateChromium.enable or true;
      description = ''
        Install Chromium. On Linux this uses `pkgs.chromium`. On macOS
        this declares a Homebrew cask for the official Chromium app.
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    home.packages =
      lib.optionals cfg.signal.enable [ pkgs.signal-desktop ]
      ++ lib.optionals (cfg.chromium.enable && pkgs.stdenv.isLinux) [ pkgs.chromium ]
      ++ lib.optionals (cfg.tailscale.enable && pkgs.stdenv.isLinux) [ pkgs.tailscale ];

    services.syncthing = lib.mkIf cfg.syncthing.enable {
      enable = true;
      extraOptions = [ "--allow-newer-config" ];
    };

    # Only write Brewfile.personal on Darwin and only when at least
    # one cask is selected. Skipping the file entirely when empty
    # keeps `setup.sh` quiet on unaffected hosts.
    xdg.configFile."dotfiles-managed/Brewfile.personal" = lib.mkIf (
      pkgs.stdenv.isDarwin && personalBrewfileLines != [ ]
    ) { text = personalBrewfileText; };
  };
}
