set-option -g default-terminal "tmux-256color"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# Allow saving/restoring sessions (by default, saves/restores are done manually)
set -g @resurrect-auto-restore 'on'
# Autosave/autoload by session name
set -g @continuum-restore 'on'

set -g mouse

# Invert default split bindings: " for horizontal, % for vertical
unbind '"'
unbind %
bind '"' split-window -h
bind % split-window -v

run '~/.tmux/plugins/tpm/tpm'
