repos_dir = "~/dev/repos"
wt_dir = "~/dev/wt"
detached_dir = "~/dev/detached"

[[install]]
repo = "github.com/tsauvajon/goto"

[[install]]
repo = "github.com/tsauvajon/task"

[[install]]
repo = "github.com/bahdotsh/mdterm"

[[install]]
repo = "github.com/jrobhoward/dumap"
