# https://github.com/NicholasSebastian/dotfiles

monitor = DP-2,5120x2160@120,auto,1

source = ~/.config/hypr/env.conf
source = ~/.config/hypr/style.conf
source = ~/.config/hypr/rules.conf
source = ~/.config/hypr/keybinds.conf

exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

exec-once = waybar &
exec-once = mako &

# bind = ALT, Tab, cyclenext
# bind = SUPER, RETURN, exec, alacritty
# bind = SUPER, M, exit
# bind = SUPER, Q, killactive
# bind = SUPER, F, fullscreen
# bind = SUPER, T, togglefloating
# bind = SUPER, H, movefocus, l
# bind = SUPER, L, movefocus, r
# bind = SUPER, K, movefocus, u
# bind = SUPER, J, movefocus, d

