general {
	col.active_border = rgba(f38ba8ff) rgba(74c7ecff) 45deg
	col.inactive_border = rgba(50536aff)

	gaps_in = 5
	gaps_out = 0,10
	border_size = 2

	layout = dwindle
	allow_tearing = true # was false, ChatGPT told me to set it to true for better framerate

	resize_on_border = true # resize with the mouse
	extend_border_grab_area = 10
	hover_icon_on_border = true
}

input {
	kb_layout = us
	kb_variant = altgr-intl 
	follow_mouse = 2 # clicking on a window focuses the keyboard on it
	natural_scroll = true # macOs style
}

cursor {
	no_hardware_cursors = true # Nvidia fails to show cursor sometimes
	no_warps = true
	enable_hyprcursor = true
	default_monitor = DP-2	
}

decoration {
	rounding = 10
	active_opacity = 1.0
	fullscreen_opacity = 1.0
	inactive_opacity = 0.95

	blur {
		enabled = true
		size = 4
		passes = 3
		new_optimizations = true
	}

	shadow {
		enabled = true
		offset = 5 5
		range = 25
		render_power = 4
		ignore_window = false
		color = rgba(18192688)
		color_inactive = rgba(00000088)
	}
}

animations {
	enabled = true
	
	bezier = wind, 0.05, 0.9, 0.1, 1.0
	bezier = winIn, 0.1, 1.0, 0.1, 1.0
	bezier = winOut, 0.3, -0.3, 0, 1
	bezier = liner, 1, 1, 1, 1

	animation = windows, 1, 6, wind, slide
	animation = windowsIn, 1, 6, winIn, slide
	animation = windowsOut, 1, 5, winOut, slide
	animation = windowsMove, 1, 5, wind, slide

	animation = border, 1, 1, liner
	animation = borderangle, 1, 30, liner, loop
	animation = fade, 1, 10, default
	animation = workspaces, 1, 5, wind
}

misc {
	render_unfocused_fps = 60
	disable_hyprland_logo = true # Anime girl in the background
	force_default_wallpaper = 0 # Anime girl wallpaper
	disable_splash_rendering = true
	vfr = false # Save power when enable, maybe makes long-unfocused windows be ultra laggy (e.g. WoW)
	vrr = 2 # Adaptative sync when in games (?)
	# render_ahead_of_time = true # ChatGPT suggestion to stabilise games

	focus_on_activate = true # Focus newly opened windows
	mouse_move_focuses_monitor = true
	# new_window_takes_over_fullscreen = 2 # Focus new window when opened, even if fullscreen
}

dwindle {
	pseudotile = true
	preserve_split = true
}

xwayland {
	force_zero_scaling = true # Fixes VS Code
}

plugin {
	hyprwinwrap {
		class = kitty-bg
	}
}
