#!/usr/bin/env bash
# Dry-run cleanup for Homebrew casks not declared in any managed Brewfile.
#
# "Managed" means:
#   - $DOTFILES/config/Brewfile                          (public, hand-edited)
#   - ~/.config/dotfiles-managed/Brewfile.personal       (Home Manager-generated
#                                                         from `home/personal.nix`,
#                                                         present only when at
#                                                         least one personal cask
#                                                         toggle is on)
#
# A cask is "extra" if it is currently installed and absent from both files.
# Extras are listed by default; pass --apply to uninstall them. setup.sh
# invokes this script with --apply so personal toggles reconcile fully:
# turning a `dotfiles.personal.*.enable` toggle off removes its line from
# Brewfile.personal, which in turn makes its cask an "extra" on the next
# setup.sh run, which then uninstalls it.
set -euo pipefail

apply=0
DOTFILES="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)"
public_brewfile="$DOTFILES/config/Brewfile"
# Personal Brewfile is generated by Home Manager via xdg.configFile. This
# dotfiles config leaves xdg.configHome at its default, so it is expected
# under $HOME/.config.
personal_brewfile="$HOME/.config/dotfiles-managed/Brewfile.personal"

usage() {
  cat <<EOF
Usage: scripts/brew-cleanup.sh [--apply]

Lists installed Homebrew casks that are not declared in:
  - $public_brewfile
  - $personal_brewfile (when present)

By default this is a dry run. Pass --apply to uninstall the extra casks.
EOF
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --apply)
      apply=1
      ;;
    --dry-run)
      apply=0
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      printf 'error: unknown argument: %s\n' "$1" >&2
      usage >&2
      exit 2
      ;;
  esac
  shift
done

if [ "$(uname -s)" != "Darwin" ]; then
  printf 'Homebrew cask cleanup is only supported on macOS.\n'
  exit 0
fi

if ! command -v brew >/dev/null 2>&1; then
  printf 'error: brew not found on PATH\n' >&2
  exit 1
fi

if [ ! -f "$public_brewfile" ]; then
  printf 'error: Brewfile not found: %s\n' "$public_brewfile" >&2
  exit 1
fi

# Personal Brewfile is optional; reading a missing file via sed below would
# fail, so build the list of inputs explicitly.
brewfiles=("$public_brewfile")
if [ -f "$personal_brewfile" ]; then
  brewfiles+=("$personal_brewfile")
fi

tmpdir=$(mktemp -d)
trap 'rm -rf "$tmpdir"' EXIT

wanted="$tmpdir/wanted-casks"
installed="$tmpdir/installed-casks"
extras="$tmpdir/extra-casks"

sed -nE 's/^[[:space:]]*cask[[:space:]]+"([^"]+)".*/\1/p' "${brewfiles[@]}" | sort -u > "$wanted"
brew list --cask -1 | sort -u > "$installed"
comm -23 "$installed" "$wanted" > "$extras"

if [ ! -s "$extras" ]; then
  printf 'No extra Homebrew casks found.\n'
  exit 0
fi

if [ "$apply" -eq 0 ]; then
  printf 'Extra Homebrew casks not declared in any managed Brewfile:\n'
  while IFS= read -r cask; do
    printf '  %s\n' "$cask"
  done < "$extras"
  printf '\nDry run only. Pass --apply to uninstall these casks.\n'
  exit 0
fi

while IFS= read -r cask; do
  [ -z "$cask" ] && continue
  brew uninstall --cask "$cask"
done < "$extras"
