import { statSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import type { Plugin } from "@opencode-ai/plugin";

// Passphrase-less SSH signing key dedicated to OpenCode-generated commits.
// Generated by scripts/bootstrap-keys.sh inside the private overlay, so the
// public repo never contains key material. When present, every git commit or
// tag made from an OpenCode shell session is signed with this key instead of
// the interactive personal one (which lives behind an ssh-agent passphrase).
const SIGNING_KEY_RELPATH = join(".config", "dotfiles", "keys", "opencode-git-signing");

function signingPrivateKeyPath(home?: string): string | undefined {
  const root = home ?? homedir();
  if (!root) {
    return undefined;
  }

  const candidate = join(root, SIGNING_KEY_RELPATH);
  try {
    if (!statSync(candidate).isFile()) {
      return undefined;
    }
    return candidate;
  } catch {
    return undefined;
  }
}

type GitConfigEntry = readonly [name: string, value: string];

function signingConfigEntries(keyPath: string): readonly GitConfigEntry[] {
  return [
    ["gpg.format", "ssh"],
    ["user.signingkey", keyPath],
    ["commit.gpgsign", "true"],
    ["tag.gpgsign", "true"],
  ] as const;
}

// Returns the user.signingkey value already configured via GIT_CONFIG_* env
// entries, if any. Later GIT_CONFIG entries override earlier ones in git, so
// callers can safely append their own key after a foreign one.
function existingSigningKey(env: Record<string, string | undefined>): string | undefined {
  const count = Number.parseInt(env.GIT_CONFIG_COUNT ?? "", 10);
  if (!Number.isInteger(count) || count <= 0) {
    return undefined;
  }

  for (let index = 0; index < count; index += 1) {
    if (env[`GIT_CONFIG_KEY_${index}`] === "user.signingkey") {
      const value = env[`GIT_CONFIG_VALUE_${index}`];
      if (value !== undefined) {
        return value;
      }
    }
  }
  return undefined;
}

// Builds GIT_CONFIG_* env entries that force SSH commit/tag signing with
// keyPath, appended after whatever entries already exist (so other tooling
// injecting git config keeps working). Returns null when this exact key is
// already configured, to avoid redundant re-injection.
function gitSigningEnv(
  keyPath: string,
  env: Record<string, string | undefined>,
): Record<string, string> | null {
  if (existingSigningKey(env) === keyPath) {
    return null;
  }

  const existingCount = Number.parseInt(env.GIT_CONFIG_COUNT ?? "", 10);
  let index = Number.isInteger(existingCount) && existingCount > 0 ? existingCount : 0;

  const result: Record<string, string> = {};
  for (const [name, value] of signingConfigEntries(keyPath)) {
    result[`GIT_CONFIG_KEY_${index}`] = name;
    result[`GIT_CONFIG_VALUE_${index}`] = value;
    index += 1;
  }
  result.GIT_CONFIG_COUNT = String(index);
  return result;
}

const GitSigningPlugin = (async () => ({
  "shell.env": async (_input, output) => {
    const keyPath = signingPrivateKeyPath(process.env.HOME);
    if (!keyPath) {
      return;
    }

    const injected = gitSigningEnv(keyPath, { ...process.env, ...output.env });
    if (!injected) {
      return;
    }
    Object.assign(output.env, injected);
  },
})) satisfies Plugin;

const testHelpers = Object.freeze({
  SIGNING_KEY_RELPATH,
  signingPrivateKeyPath,
  signingConfigEntries,
  existingSigningKey,
  gitSigningEnv,
});

Object.defineProperty(GitSigningPlugin, "_test", { value: testHelpers });

export default GitSigningPlugin as typeof GitSigningPlugin & { readonly _test: typeof testHelpers };
